/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Simpson = new javax.swing.JButton();
        GaussSeidel = new javax.swing.JButton();
        FalsePosition = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Simpson.setBorderPainted(false);
        Simpson.setContentAreaFilled(false);
        Simpson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpsonActionPerformed(evt);
            }
        });
        getContentPane().add(Simpson, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 140, 40));

        GaussSeidel.setBorderPainted(false);
        GaussSeidel.setContentAreaFilled(false);
        GaussSeidel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GaussSeidelActionPerformed(evt);
            }
        });
        getContentPane().add(GaussSeidel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 140, 40));

        FalsePosition.setBorderPainted(false);
        FalsePosition.setContentAreaFilled(false);
        FalsePosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FalsePositionActionPerformed(evt);
            }
        });
        getContentPane().add(FalsePosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Numericals.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 576));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FalsePositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FalsePositionActionPerformed
      new FalsePositionMethod().setVisible(true);
      dispose();
    }//GEN-LAST:event_FalsePositionActionPerformed

    private void GaussSeidelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GaussSeidelActionPerformed
       new GuessSeidel().setVisible(true);
       dispose();
    }//GEN-LAST:event_GaussSeidelActionPerformed

    private void SimpsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpsonActionPerformed
        new Simpson().setVisible(true);
        dispose();
    }//GEN-LAST:event_SimpsonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FalsePosition;
    private javax.swing.JButton GaussSeidel;
    private javax.swing.JButton Simpson;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
